# These file filter patterns are used by the action https://github.com/dorny/paths-filter

backend-test-lint-code: &backend-test-lint-code
  - '**/*'

backend-test-unit-code: &backend-test-unit-code
  - '**/*'

backend-test-build-code: &backend-test-build-code
  - '**/*'

backend-test-build-docker: &backend-test-build-docker
  - '**/*'

backend-test-build-docs: &backend-test-build-docs
  - '**/*.md'
  - '.github/workflows/backend.deploy.docs.yml'
  - '.vuepress/*'
  - 'package.json'